apiVersion: v1
kind: Service
metadata:
  name: paiban-service
  namespace: paiban
  labels:
    app: paiban
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 7012
      protocol: TCP
      name: http
  selector:
    app: paiban
---
apiVersion: v1
kind: Service
metadata:
  name: paiban-headless
  namespace: paiban
  labels:
    app: paiban
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 7012
      targetPort: 7012
      protocol: TCP
      name: http
  selector:
    app: paiban

